#!/bin/sh

item='#'

getopt() { item=$1; title_=$2; }
getopt $menu_

. $cgi_/head

list="home:home
apps:apps
wincfg:wins
scrcfg:screens
tagcfg:tags
netcfg:network"

echo '</head>
<body>
<header>
<div class=menu>
<table class=blank>
<tr>'

if [ "$item" = "home" ]; then
	style='style=color:#444;'
fi

echo "<td class=home>
<span>&nbsp;</span>
<a class=home $style href=cgi?home>&#xf015;</a>
<span>&nbsp;</span>
</td>
<td>
<ul class=menu>"

for item in $list; do
	getvar_ ':' $item
	getval_ ':' $item

	if [ "$var_" = "home" ]; then
		continue
	fi

	if [ "$title_" = "$val_" -a "$var_" != "home" ]; then
		class="active"
	else
		class="menu"
	fi

	echo "<li class=$class><a href=cgi?$var_>$val_</a></li>"
done
echo '</ul>
</td>
</tr>
</table>
</div>
</header><div style=margin:8px>'
