#!/bin/sh

menu_="netcfg route"
. $cgi_/menu "netcfg" "route"
. $lib_/libnet

head()
{
	echo "<tr>"
	while [ $# -ne 0 ]; do
		echo "<td $class_>$1</td>"
		shift 1
	done
	echo "</tr>"
}

route()
{
	alter_
	echo "<tr>"
	local i=0
	while [ $# -ne 0 ]; do
		if [ $i -eq 1 -o $i -eq 2 -o $i -eq 7 ]; then
			hex2ip4_ $1
			str=$ip4addr_
		else
			str=$1
		fi
		echo "<td $class_>$str&nbsp;</td>"
		shift 1
		i=$((i + 1))
	done
	echo "</tr>"
}

echo "<table class=blank>
<tr>
<td class=para>
<a class=menu href=cgi?netcfg><div class=para>${sym4_}route</div></a>
</td>
</tr>
<tr>
<td>
<table class=legend>
<tr><td><br></td></tr>"
row_=0
while read line; do
	case $line in
	Iface*) class_=" class=info"; head $line;;
	*) route $line;;
	esac
done < /proc/net/route
echo '</table>
</table>'

. $cgi_/tail
