#!/bin/sh

menu_="wincfg wins"
. $cgi_/menu

color1="#f8f8f8"
color2="#101010"
image=''
w=24
h=24

ctl_=$HOME/.yawm/.control
cli_=$HOME/.yawm/clients

echo list-clients > $ctl_

while read var val; do
	case "$var" in
	seq*) seq=$val;;
	esac
done < $cli_

echo list-clients > $ctl_

found=0
count=0
while :; do
	while read var val; do
		case "$var" in
		seq*)
			if [ "$seq" != "$val" ]; then
				found=1
				break
			fi
			;;
		esac
	done < $cli_
	if [ $found -eq 1 -o $count -gt 500 ]; then
		break
	fi
	count=$((count + 1))
	sleep 0.1
done

echo "<table class=blank>
<tr>
<td class=info style=text-align:center;>&#xf057;&nbsp;</td>
<td class=info>title</td>
<td class=info>command</td>
<td class=info>process</td>
<td class=info>window</td>
</tr>"
while read scr tag win status pid title; do
	case $scr in
	seq*) continue;;
	esac

	i=$((i + 1))
	if [ $((i % 2)) -eq 0 ]; then
		style=''
		bgcolor="transparent"
	else
		style="style=background-color:$color1;"
		bgcolor="$color1"
	fi

	if [ $pid -ne 0 ]; then
		while read val; do cmd=$val; done < /proc/$pid/comm
	fi

	icon=$(xprop -id $win | grep -E "^WM_CLASS.*=" | cut -f2 -d'"')
	case "$icon" in
	*[Tt]erm*) glyph="[&#xf120;";;
	[Cc][Pp][Uu]*|*[Mm]on*) glyph="&#xf1fe;";;
	*[Dd]ict*) glyph="&#xf02d;";;
	[Nn]avigator|[Bb]rowser) glyph="&#xf0ac;";;
	[Cc]hrom*) glyph="&#xf268;";;
	[Ff]irefox) glyph="&#xf269;";;
	*[Cc]lock*) glyph="&#xf017;";;
	*) glyph="&#xf013;";;
	esac
	echo "<tr $style>
<td>
<a class=symbol style=color:#DE5958; href=cgi?close=$win>&#xf00d;&nbsp;</a>
</td>
<td class=pad>
<form action=cgi? method=get>
<button class=framed title=show window type=submit name=close value=$win>
<table class=button>
<tr>
<td class=pad>$glyph&nbsp;&nbsp;$title</td>
</tr>
</table>
</button>
</form>
</td>
<td class=pad title=command>$cmd</td>
<td class=pad><a href=cgi?pidinfo=$pid title='show details'>$pid</a></td>
<td class=pad><a href=cgi?wininfo=$win title='show details'>$win</a></td>
</tr>"
done < $cli_
echo '</table>'

. $cgi_/tail
