#!/bin/sh

sudo ifconfig $iface up 1>&2
sudo wpa_cli scan $iface 1>&2
sleep 2

echo "<tr><td><hr class=dashed></td></tr>
<tr>
<td>
<table class=blank style=width:100%;>
<tr>
<td class=info>network</td>
<td class=info>signal</td>
<td class=info>&nbsp;frequency</td>
<td class=info>hotspot</td>
</tr>
<tr><td></td></tr>"
row_=0
title=''
sudo wpa_cli scan_results | while read bssid freq sig flg ssid; do
	trace_ "$bssid | $freq | $sig | $flg | $ssid"
	case "$bssid" in
	Selected|OK|bssid) continue;;
	esac
	if [ $freq -lt 5000 ]; then
		frq="2.4GHz"
	else
		frq="5GHz"
	fi
	if [ "$flg" = "[ESS]" ]; then
		lock="&#xf09c;" # open
	else
		lock="&#xf023;"
	fi
	alter_
	lvl="&nbsp;"
	if [ $sig -gt -50 ]; then
		clr="#111"
		# last &#9633 is for aesthetic reason
		lvl="&#9632;&#9632;&#9632;&#9632;&#9633;&nbsp;$sig"
		sig="excellent"
	elif [ $sig -le -50 -a $sig -ge -60 ]; then
		clr="#555"
		lvl="&#9632;&#9632;&#9632;&#9633;&#9633;&nbsp;$sig"
		sig="good"
	elif [ $sig -lt -60 -a $sig -ge -70 ]; then
		clr="#777"
		lvl="&#9632;&#9632;&#9633;&#9633;&#9633;&nbsp;$sig"
		sig="fair"
	else
		clr="#aaa"
		lvl="&#9632;&#9633;&#9633;&#9633;&#9633;&nbsp;$sig"
		sig="weak"
	fi
	echo "<tr>
<td $class_>
<div>
<a class=hide id=hide$row_ href=#hide$row_>$lock &#xf0da; $ssid</a>
<a class=show id=show$row_ href=#show$row_>$lock &#xf0d7; $ssid</a>
<div class=details style=margin:4px;>
<form name=$row_ action=cgi? method=post>
<input name=post.wpa type=hidden>
<input name=dev value=$iface type=hidden>
<span class=symbol>&nbsp;&#xf084;&nbsp;</span>
<input class=text type=text name=username value=$ssid hidden>
<input class=text type=password name=key title=key>
<input class=symbol type=submit value=&#xf090; title=connect>
</form>
</div>
</div>
</td>
<td $class_ title=$sig style=color:$clr;>$lvl</td>
<td $class_ title=$freq>&nbsp;$frq</td>
<td $class_>&nbsp;$bssid</td>
</tr>"
done
echo '</table>'
